export const LOGIN_TYPES = Object.freeze({
  SET_AUTH: 'SET_AUTH',
})

export const SEARCH_PAGE_TYPES = Object.freeze({
  SET_SEARCH_WORD: 'SET_SEARCH_WORD',
  SET_SEARCH_MOVIES: 'SET_SEARCH_MOVIES',
  SET_SEARCH_SHOWS: 'SET_SEARCH_SHOWS',
  SET_FETCHING: 'SET_FETCHING',
  SET_ERROR: 'SET_ERROR',
  SET_MOVIES_PAGE: 'SET_MOVIES_PAGE',
  SET_SHOWS_PAGE: 'SET_SHOWS_PAGE'
})

export const CURRENT_FILM_PAGE_TYPES = Object.freeze({
  SET_FETCHING: 'SET_FETCHING',
  SET_ERROR: 'SET_ERROR',
  SET_FILM_DATA: 'SET_FILM_DATA',
})

export const MOVIES_PAGE_TYPES = Object.freeze({
  SET_FETCHING: 'SET_FETCHING',
  SET_ERROR: 'SET_ERROR',
  SET_MOVIES_DATA: 'SET_MOVIES_DATA',
  SET_PAGE: 'SET_PAGE',
  SET_CLEAN_MOVIES_STATE: 'SET_CLEAN_MOVIES_STATE',
})
