export const LOGIN_TYPES = Object.freeze({
  SET_AUTH: 'SET_AUTH',
})

export const SEARCH_PAGE_TYPES = Object.freeze({
  SET_SEARCH_WORD: 'SET_SEARCH_WORD',
  SET_SEARCH_DATA: 'SET_SEARCH_DATA',
  SET_FETCHING: 'SET_FETCHING',
  SET_ERROR: 'SET_ERROR',
  SET_SEARCH_PAGE: 'SET_SEARCH_PAGE',
})

export const CURRENT_FILM_PAGE_TYPES = Object.freeze({
  SET_FETCHING: 'SET_FETCHING',
  SET_ERROR: 'SET_ERROR',
  SET_FILM_DATA: 'SET_FILM_DATA',
})

export const MOVIES_PAGE_TYPES = Object.freeze({
  SET_MOVIES_FETCHING: 'SET_MOVIES_FETCHING',
  SET_ERROR: 'SET_ERROR',
  SET_MOVIES_DATA: 'SET_MOVIES_DATA',
})
